version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: MicroServicoReview
    command: sh -c "cd MicroServicoReview && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    #env_file:
    #  - .env
    #depends_on:
    #  - db:
    #      condition: service_healthy
volumes:
  data: