version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - data:/var/lib/mysql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=django
      - POSTGRES_DB=microservicoreview
    ports:
      - "8001:5432"

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: MicroServicoReview
    command: sh -c "cd MicroServicoReview && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  data: